from .calcular_existencias import calcular_existencias
from .unidades_totales import calcular_unidades_totales
from .garage_menor import garage_con_menos_unidades
from .obtener_recaudacion import obtener_recaudacion
from .garages_mas_de_6 import calcular_garages_6_mas